name: setup
description: setup
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        cache: pnpm
        registry-url: 'https://registry.npmjs.org'
    - run: pnpm install
      shell: bash
